---
language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - commitlint-travis
  - npm run lint
  - npm run build
  - npx nyc npm test
after_success:
  - npx nyc report --reporter=text-lcov > coverage.lcov
  - npx codecov
