---
language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - commitlint-travis
  - npm run lint
  - npm run test
  - npm run build
after_success:
  - npx codecov
